# Generated by Django 2.1.7 on 2019-05-07 06:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190423_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('ed455a76-f97b-46a9-9566-66eb26828c5d')),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 8, 19, 7, 809426)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='hand_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 8, 19, 7, 809426)),
        ),
    ]
