# Generated by Django 2.1.7 on 2019-05-14 07:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190507_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_api_id',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('af8ced22-765a-43fb-babd-fa0783efff67')),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 9, 1, 32, 264082)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 9, 1, 32, 264082)),
        ),
    ]
