# Generated by Django 2.1.7 on 2019-05-29 09:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190514_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('ea595717-9778-4965-9f0c-9c25d08061d7')),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 11, 40, 11, 641991)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 11, 40, 11, 641991)),
        ),
    ]
