# Generated by Django 2.1.7 on 2019-06-13 06:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190529_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='broken',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='stock',
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='return_state',
            field=models.CharField(blank=True, choices=[('as_borrowed', 'As Borrowed'), ('damaged', 'Damaged'), ('broken', 'Broken')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='broken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('8a8c92e3-9776-4203-9da2-a3f896eb55ea')),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 8, 22, 28, 611211)),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 8, 22, 28, 611211)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='TechLab/static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
